# Generated by Django 3.2 on 2024-07-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code',
            new_name='confirmation_code',
        ),
    ]
