# Generated by Django 3.2 on 2024-07-31 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240731_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
